name: HawkEye
main: uk.co.oliwali.HawkEye.HawkEye
author: oliverw92
version: 1.0.5b
description: Track those griefers like a bird of prey!
softdepend: [WorldEdit,PermissionsEx,Permissions,GroupManager,bPermissions]
commands:
  hawk:
    description: Track those griefers like a bird of prey!
    aliases: [hawkeye,he,hk,ha]
    usage: /<command> help
permissions:
    hawkeye.*:
        description: Gives access to all HawkEye commands
        children:
            hawkeye.search: true
            hawkeye.tpto: true
            hawkeye.rollback: true
            hawkeye.tool: true
            hawkeye.notify: true
            hawkeye.preview: true
    hawkeye.tool.*:
        description: Permission to use the HawkEye tool
        children:
            hawkeye.tool.bind: true
